# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=120, verbose_name='category name')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
